/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package s3_02_n3_pablogarciabarros;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
